apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - fraud-detection
  selector:
    matchLabels:
      app: fraud-scoring
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
