apiVersion: v1
kind: Service
metadata:
  name: fraud-preview
  namespace: fraud-detection
  labels:
    app: fraud-scoring
spec:
  selector:
    app: fraud-scoring
  ports:
    - name: http
      port: 80
      targetPort: 8000
